version: '2.1'

services:
  endakelly-spring4:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/labs/endakelly-spring4
    ports:
      - $SERVER_PORT:$SERVER_PORT
